### ISSUE TITLE
ScanCode not able to extract AssertJ license/copyright data

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#2944]
This is a follow up of the discussion in #2930.

## Deliverables
- [ ] A ScanCode execution on AssertJ should return the expected data (details to be clarified)
- [ ] (Optional) AssertJ has a workflow job based on ScanCode that breaks if the license/copyright data is no longer provided in the expected format

**Comment by scordio** [comment]
@tobi5775 would you be able to provide the ScanCode execution details for AssertJ so we can make sure we're covering your use case?

**Comment by tobi5775** [comment]
@scordio sure no problem!

We get this:
```yaml
{
      "path": "assertj-core-3.25.0-SNAPSHOT.jar-extract/META-INF/maven/org.assertj/assertj-core/pom.xml",
      "type": "file",
      "name": "pom.xml",
      "base_name": "pom",
      "extension": ".xml",
      "size": 19785,
      "date": "2023-02-07",
      "sha1": "361e0f3ca14dc63a3e9a062658ecddd3961866d7",
      "md5": "847a740e2447fe153c55a78ed53d2c2b",
      "sha256": "3fce3a7bf490560b187858bd7c1409c5b8556be7c9795fc4af353ffe04cf6632",
      "mime_type": "text/xml",
      "file_type": "XML 1.0 document, ASCII text, with CRLF line terminators",
      "programming_language": null,
      "is_binary": false,
      "is_text": true,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "urls": [
        {
          "url": "http://maven.apache.org/xsd/maven-4.0.0.xsd",
          "start_line": 2,
          "end_line": 2
        },
        {
          "url": "https://github.com/assertj/assertj/issues/1403",
          "start_line": 436,
          "end_line": 436
        },
        {
          "url": "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js",
          "start_line": 446,
          "end_line": 446
        }
      ],
      "is_license_text": false,
      "files_count": 0,
      "dirs_count": 0,
      "size_count": 0,
      "scan_errors": []
    }
```

But We expect something like this:

```yaml
 {
      "path": "assertj-core-3.25.0-SNAPSHOT.jar-extract/META-INF/maven/org.assertj/assertj-core/pom.xml",
      "type": "file",
      "name": "pom.xml",
      "base_name": "pom",
      "extension": ".xml",
      "size": 20379,
      "date": "2023-02-07",
      "sha1": "076d4eb69a1172d7816b126030a059eb55b37197",
      "md5": "a343a38e9925d34821434895a98b716d",
      "sha256": "5354ce05ffdd53fa2a56ef0715e1b42b3a13d3e0be6c4eca0a292c594283056f",
      "mime_type": "text/xml",
      "file_type": "XML 1.0 document, ASCII text, with CRLF line terminators",
      "programming_language": null,
      "is_binary": false,
      "is_text": true,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "licenses": [
        {
          "key": "apache-2.0",
          "score": 100.0,
          "name": "Apache License 2.0",
          "short_name": "Apache 2.0",
          "category": "Permissive",
          "is_exception": false,
          "is_unknown": false,
          "owner": "Apache Software Foundation",
          "homepage_url": "http://www.apache.org/licenses/",
          "text_url": "http://www.apache.org/licenses/LICENSE-2.0",
          "reference_url": "https://scancode-licensedb.aboutcode.org/apache-2.0",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml",
          "spdx_license_key": "Apache-2.0",
          "spdx_url": "https://spdx.org/licenses/Apache-2.0",
          "start_line": 3,
          "end_line": 10,
          "matched_rule": {
            "identifier": "apache-2.0_7.RULE",
            "license_expression": "apache-2.0",
            "licenses": [
              "apache-2.0"
            ],
            "referenced_filenames": [],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": false,
            "has_unknown": false,
            "matcher": "2-aho",
            "rule_length": 85,
            "matched_length": 85,
            "match_coverage": 100.0,
            "rule_relevance": 100
          },
          "matched_text": "Licensed under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with\r\nthe License. You may obtain a copy of the License at\r\n\r\nhttp://www.apache.org/licenses/LICENSE-2.0\r\n\r\nUnless required by applicable law or agreed to in writing, software distributed under the License is distributed on\r\nan \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the\r\nspecific language governing permissions and limitations under the License."
        }
      ],
      "license_expressions": [
        "apache-2.0"
      ],
      "percentage_of_license_text": 5.11,
      "copyrights": [
        {
          "copyright": "Copyright 2012-2023 the original author or authors",
          "start_line": 12,
          "end_line": 12
        }
      ],
      "holders": [
        {
          "holder": "the original author or authors",
          "start_line": 12,
          "end_line": 12
        }
      ],
      "authors": [],
      "urls": [
        {
          "url": "http://www.apache.org/licenses/LICENSE-2.0",
          "start_line": 6,
          "end_line": 6
        },
        {
          "url": "http://maven.apache.org/xsd/maven-4.0.0.xsd",
          "start_line": 14,
          "end_line": 14
        },
        {
          "url": "https://github.com/assertj/assertj/issues/1403",
          "start_line": 448,
          "end_line": 448
        },
        {
          "url": "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js",
          "start_line": 458,
          "end_line": 458
        }
      ],
      "is_license_text": false,
      "files_count": 0,
      "dirs_count": 0,
      "size_count": 0,
      "scan_errors": []
    }
```
